//Creacion del objeto Usuarios(tendremos algunos precargados)CORROBORAR DSP CON EL CONSTRUCTOR
const usuariosLocal = [
  {
    id: "1",
    nombreCompleto: "Lo de Pepe",
    usuario: "lodepepe",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 30,
    cuposDisponibles: 22, //la direrencia entre maximos y los reservados en estado pendiente
    calificacion: 0,
    tipo: "local",
    rubro: "restaurant",
    imagen:
      '<img src="./Imagenes/Restaurant 1.jpg" alt="Lo de Pepe foto" style="width:200px">',
  },
  {
    id: "2",
    nombreCompleto: "Garage Burguer",
    usuario: "garageburguer",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 45,
    cuposDisponibles: 43,
    calificacion: 0,
    tipo: "local",
    rubro: "restaurant",
    imagen:
      '<img src="./Imagenes/Restaurant 2.jpg" alt="Garage burguer foto" style="width:200px">',
  },
  {
    id: "3",
    nombreCompleto: "Lisa",
    usuario: "lisa",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 25,
    cuposDisponibles: 25,
    calificacion: 0,
    tipo: "local",
    rubro: "restaurant",
    imagen:
      '<img src="./Imagenes/Restaurant 3.jpg" alt="Lisa foto" style="width:200px">',
  },
  {
    id: "4",
    nombreCompleto: "El Galpon",
    usuario: "elgalpon",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 200,
    cuposDisponibles: 200,
    calificacion: 0,
    tipo: "local",
    rubro: "teatro",
    imagen:
      '<img src="./Imagenes/Teatro 1.jpg" alt="El Galpon foto" style="width:200px">',
  },
  {
    id: "5",
    nombreCompleto: "El Tinglado",
    usuario: "eltinglado",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 157,
    cuposDisponibles: 157,
    calificacion: 0,
    tipo: "local",
    rubro: "teatro",
    imagen:
      '<img src="./Imagenes/Teatro 2.jpg" alt="El Tinglado foto" style="width:200px">',
  },
  {
    id: "6",
    nombreCompleto: "Museo Del Prado",
    usuario: "delprado",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 100,
    cuposDisponibles: 98,
    calificacion: 0,
    tipo: "local",
    rubro: "museo",
    imagen:
      '<img src="./Imagenes/Museo 1.jpg" alt="Museo del Prado foto" style="width:200px">',
  },
  {
    id: "7",
    nombreCompleto: "Louvre",
    usuario: "louvre",
    contraseña: "1",
    habilitado: true,
    cuposMaximos: 159,
    cuposDisponibles: 146,
    calificacion: 0,
    tipo: "local",
    rubro: "museo",
    imagen:
      '<img src="./Imagenes/Museo 4.jpg" alt="Louvre foto" style="width:200px">',
  },
];

const reservas = [
  {
    id: 1,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Emiliano Lujan",
    cupos: 2,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 2,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Jose Diaz",
    cupos: 3,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 3,
    nombreCompletoLocal: "Louvre",
    idLocal: 7,
    nombreCompletoPersona: "Jose Diaz",
    rubro: "museo",
    cupos: 10,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 4,
    nombreCompletoLocal: "Garage Burguer",
    idLocal: 2,
    nombreCompletoPersona: "Emiliano Lujan",
    cupos: 2,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 5,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Jose Diaz",
    cupos: 15,
    status: "FINALIZADO",
    calificacion: 5,
  },
  {
    id: 6,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Gustavo Brañas",
    cupos: 3,
    status: "FINALIZADO",
    calificacion: 3,
  },
  {
    id: 7,
    nombreCompletoLocal: "Garage Burguer",
    idLocal: 2,
    nombreCompletoPersona: "Gustavo Brañas",
    cupos: 3,
    status: "FINALIZADO",
    calificacion: 0,
  },
  {
    id: 8,
    nombreCompletoLocal: "El Tinglado",
    idLocal: 5,
    nombreCompletoPersona: "Gustavo Brañas",
    cupos: 3,
    status: "FINALIZADO",
    calificacion: 0,
  },
  {
    id: 9,
    nombreCompletoLocal: "Louvre",
    idLocal: 7,
    nombreCompletoPersona: "Gustavo Brañas",
    cupos: 3,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 10,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Gustavo Brañas",
    cupos: 3,
    status: "CANCELADO",
    calificacion: 0,
  },
  {
    id: 11,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Mailen Arleo",
    cupos: 3,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 12,
    nombreCompletoLocal: "Louvre",
    idLocal: 7,
    nombreCompletoPersona: "Jose Diaz",
    rubro: "museo",
    cupos: 50,
    status: "FINALIZADO",
    calificacion: 2,
  },
  {
    id: 13,
    nombreCompletoLocal: "Louvre",
    idLocal: 7,
    nombreCompletoPersona: "Mailen Arleo",
    rubro: "museo",
    cupos: 50,
    status: "FINALIZADO",
    calificacion: 3,
  },
  {
    id: 14,
    nombreCompletoLocal: "Lisa",
    idLocal: 3,
    nombreCompletoPersona: "Jose Diaz",
    cupos: 15,
    status: "FINALIZADO",
    calificacion: 0,
  },
  {
    id: 15,
    nombreCompletoLocal: "El Galpon",
    idLocal: 4,
    nombreCompletoPersona: "Joaco Kam",
    cupos: 2,
    status: "FINALIZADO",
    calificacion: 4,
  },
  {
    id: 16,
    nombreCompletoLocal: "Museo Del Prado",
    idLocal: 6,
    nombreCompletoPersona: "Joaco Kam",
    cupos: 2,
    status: "PENDIENTE",
    calificacion: 0,
  },
  {
    id: 17,
    nombreCompletoLocal: "Lo de Pepe",
    idLocal: 1,
    nombreCompletoPersona: "Mailen Arleo",
    cupos: 3,
    status: "CANCELADO",
    calificacion: 0,
  },
  {
    id: 18,
    nombreCompletoLocal: "Museo Del Prado",
    idLocal: 6,
    nombreCompletoPersona: "Joaco Kam",
    cupos: 3,
    status: "CANCELADO",
    calificacion: 0,
  },
];

class Reservas {
  constructor(nombreLocal, idLocal, nombrePersona, cuposSeleccionados) {
    this.id = asignacionIdReservas();
    this.nombreCompletoLocal = nombreLocal;
    this.idLocal = Number(idLocal);
    //por error se trabajo con string los id locales, se soluciona convirtiendo a number los mismos
    this.nombreCompletoPersona = nombrePersona;
    this.cupos = cuposSeleccionados;
    this.status = "PENDIENTE";
    this.calificacion = 0;
  }
}
